use numeric_enum_macro::numeric_enum;

numeric_enum! {
    #[repr(u32)]
    /// Exception codes that are stored in the `Cause` register.
    #[derive(Clone, Copy, Debug, PartialEq, PartialOrd, Ord, Eq, Hash)]
    pub enum Exception {
        /// External interrupt.
        Interrupt = 0,
        /// TLB Modification.
        TLBModification = 1,
        /// TLB Load Miss.
        TLBLoadMiss = 2,
        /// TLB Store Miss.
        TLBStoreMiss = 3,
        /// Address error exception generated by a load instruction.
        AddressLoadError = 4,
        /// Address error exception generated by a store instruction.
        AddressStoreError = 5,
        /// Instruction Bus Error.
        InstructionBusError = 6,
        /// Data Bus Error.
        DataBusError = 7,
        /// Generated unconditionally by a syscall instruction.
        Syscall = 8,
        /// Breakpoint instruction.
        Breakpoint = 9,
        /// Reserved instruction.
        ReservedInstruction = 10,
        /// Coprocessor unusable.
        CoprocessorUnusable = 11,
        /// Arithmetic Overflow.
        Overflow = 12,
        /// Trap instruction.
        TrapException = 13,

        // 13-31 Reserved on R3000, defined on later processors

        /// Unknown exception.
        Unknown = 32,
    }
}
